import * as XLSX from 'xlsx'
import { SITE_URL } from '@/lib/seo'

/**
 * CSV / XLSX export builder.
 *
 * Reuses the `xlsx` dependency already in the tree. Both formats go through the
 * same sheet model so a CSV and an XLSX of the same dataset can never drift.
 *
 * Every export carries a provenance footer — generation timestamp, row count,
 * attribution, and any caveat the data itself requires. An exported
 * spreadsheet outlives the page it came from and gets forwarded without
 * context, so a figure that means "unknown" has to say so inside the file.
 */

export type ExportFormat = 'csv' | 'xlsx'

export interface SheetColumn<T> {
  header: string
  value: (row: T) => string | number | null
}

export interface ExportSpec<T> {
  /** Becomes the filename stem and the XLSX sheet name. */
  name: string
  columns: SheetColumn<T>[]
  rows: T[]
  /** Lines appended below the data explaining provenance and limits. */
  caveats?: string[]
}

// Derived from SITE_URL rather than duplicated: an exported spreadsheet outlives
// the page it came from, so a second source of truth here would misattribute
// files indefinitely after a domain change.
const SITE = SITE_URL.replace(/^https?:\/\//, '')

function footerLines(spec: ExportSpec<unknown>, generatedAt: Date): string[] {
  return [
    '',
    `Generated by Quaestron (${SITE}) at ${generatedAt.toISOString()}`,
    `Rows: ${spec.rows.length}`,
    ...(spec.caveats ?? []),
  ]
}

/** Sheet name rules: <=31 chars, no []:*?/\ */
function safeSheetName(name: string): string {
  return name.replace(/[[\]:*?/\\]/g, '-').slice(0, 31) || 'Export'
}

function toMatrix<T>(spec: ExportSpec<T>, generatedAt: Date): (string | number | null)[][] {
  const header = spec.columns.map((c) => c.header)
  const body = spec.rows.map((row) => spec.columns.map((c) => c.value(row)))
  const footer = footerLines(spec as ExportSpec<unknown>, generatedAt).map((line) => [line])
  return [header, ...body, ...footer]
}

export interface BuiltExport {
  body: Buffer | string
  contentType: string
  filename: string
}

export function buildExport<T>(
  spec: ExportSpec<T>,
  format: ExportFormat,
  generatedAt = new Date()
): BuiltExport {
  const matrix = toMatrix(spec, generatedAt)
  const stamp = generatedAt.toISOString().slice(0, 10)
  const stem = `quaestron-${spec.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${stamp}`

  if (format === 'csv') {
    const sheet = XLSX.utils.aoa_to_sheet(matrix)
    return {
      body: XLSX.utils.sheet_to_csv(sheet),
      contentType: 'text/csv; charset=utf-8',
      filename: `${stem}.csv`,
    }
  }

  const workbook = XLSX.utils.book_new()
  const sheet = XLSX.utils.aoa_to_sheet(matrix)

  // Width the columns to their content so the file is readable on open rather
  // than a wall of ### and truncated vendor names.
  sheet['!cols'] = spec.columns.map((c, i) => {
    const longest = spec.rows.reduce((max, row) => {
      const v = c.value(row)
      return Math.max(max, v === null ? 0 : String(v).length)
    }, c.header.length)
    return { wch: Math.min(60, Math.max(10, longest + 2)), ...(i === 0 ? {} : {}) }
  })

  XLSX.utils.book_append_sheet(workbook, sheet, safeSheetName(spec.name))
  const buffer = XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }) as Buffer

  return {
    body: buffer,
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    filename: `${stem}.xlsx`,
  }
}

/** Response with the headers a browser needs to download rather than render. */
export function exportResponse(built: BuiltExport): Response {
  return new Response(built.body as BodyInit, {
    headers: {
      'Content-Type': built.contentType,
      'Content-Disposition': `attachment; filename="${built.filename}"`,
      'Cache-Control': 'no-store',
    },
  })
}

/** Formats a value for a spreadsheet cell — null stays null so Excel shows blank. */
export function cell(v: string | number | null | undefined): string | number | null {
  if (v === null || v === undefined) return null
  return v
}

/** Joins an array for a single cell without breaking CSV quoting. */
export function joinCell(values: string[] | null | undefined): string | null {
  if (!values || values.length === 0) return null
  return values.join('; ')
}
